src/components/BottomNavBar.tsx

BottomNavBar의 디자인적인 부분 제작하였습니다.
- [x ] 새로운 기능 추가
onclick을 통한 라우팅까지 구현하려 했으나, 아직 page의 이름이 정해지지 않은 관계로 조금 미루었습니다

BottomNavBar의 제작

---

package-lock.json
package.json
src/styles/GlobalStyles.ts

style: add reset css in GlobalStyles

---

src/components/TopBarText.tsx

bug : add RightClickHandler

---

src/components/TopBarText.styled.ts
src/components/TopBarText.tsx

Bug : TopBarText 레이아웃 중앙 정렬 버그 해결

---

src/pages/LoginPage/LoginPage.styled.ts
src/pages/LoginPage/LoginPage.tsx

Feat#18 login

---

.eslintrc.cjs
.prettierrc
.vscode/settings.json
package-lock.json
package.json
src/pages/ChatPage/ChatCreatePage/ChatCreatePage.styled.ts
src/pages/ChatPage/ChatCreatePage/ChatCreatePage.tsx
src/pages/ChatPage/ChatPage.tsx
vite.config.ts

- eslint 설정 수정했습니다.
- 저장하면 자동으로 import 구문 순서를 맞춰줍니다.
- 그 외 추가적인 typescript, react, prettier 등에서 권장사항을 err or warn 메세지로 띄워줍니다
- 만약 저장해도 자동으로 formatting이 안될 경우, 아래 사진처럼 setting 검색 후 default formatter는 prettier (확장프로그램 설치 필요)로 바꾸고, Format on save 옵션 체크해서 켜주면 됩니다.

Feat#eslint

---

src/App.tsx
vite.config.ts

setting: add basename for url

---

src/components/CheckBox.tsx

[BUG] #60의 checkbox 에 대한 수정

---

.gitignore
.vscode/settings.json
package-lock.json
package.json
src/apis/LoginApi.ts
src/apis/Pay/PayPageAPI.ts
src/apis/_createRequestOptions.ts
src/apis/apis.ts
src/apis/voiceroomApi.ts
src/pages/LoginPage/LoginPage.tsx
src/pages/PayPage/CompleteReqDataDiv.tsx
src/pages/PayPage/CreatePayComponents.tsx
src/pages/PayPage/CreateRequestPage.tsx
src/pages/PayPage/GrayMyReqDataDiv.tsx
src/pages/PayPage/MyReqDataDiv.tsx
src/pages/PayPage/MyRequestPayPage.tsx
src/pages/PayPage/PayPage.tsx
src/pages/PayPage/ReqDataDiv.tsx
src/pages/PayPage/RequestedPayPage.tsx
src/pages/VoiceRoomPage/JoinVoiceRoomPage.tsx
src/pages/VoiceRoomPage/VoiceRoomListPage.styled.ts
src/pages/VoiceRoomPage/VoiceRoomListPage.tsx
src/pages/VoiceRoomPage/VoiceRoomPage.tsx
src/pages/VoiceRoomPage/VoiceRoomUser.tsx
vite.config.ts

정산 API의 연동입니다
제가 정답은 아니지만, 혹시 API 연동이 익숙하지 않다면 제 코드를 참고하시면 일단 돌아는가요!
참고하셔도 좋을거 같습니다.

Feat#62 pay api

---

vite.config.ts

Reverts KUIT-Space/KUIT-Space-front#64

Revert "Update vite.config.ts"

---

src/apis/LoginApi.ts
src/pages/LoginPage/LoginPage.tsx

api: github.io proxy 안되는 문제로 back에 바로 전달하도록 변경

---

src/components/StopModal.styled.ts
src/components/StopModal.tsx
src/components/ToggleBtn.tsx
src/pages/SpacePage/AccountManage.tsx
src/pages/SpacePage/AddSpacePage.tsx
src/pages/SpacePage/AlarmManage.tsx
src/pages/SpacePage/ProfileManage.tsx
src/pages/SpacePage/SpaceOption.tsx
src/pages/SpacePage/SpacePage.tsx

Feat: 모달창 변경 및 스페이스 뷰 수정

---

.gitignore
package-lock.json
package.json
src/apis/Pay/PayPageAPI.ts
src/apis/_createRequestOptions.ts
src/apis/voiceroomApi.ts
src/pages/PayPage/CompleteReqDataDiv.tsx
src/pages/PayPage/CreatePayComponents.tsx
src/pages/PayPage/CreateRequestPage.tsx
src/pages/PayPage/GrayMyReqDataDiv.tsx
src/pages/PayPage/MyReqDataDiv.tsx
src/pages/PayPage/MyRequestPayPage.tsx
src/pages/PayPage/PayPage.tsx
src/pages/PayPage/ReqDataDiv.tsx
src/pages/PayPage/RequestedPayPage.tsx
src/pages/VoiceRoomPage/CreateVoiceRoom.tsx
src/pages/VoiceRoomPage/EditVoiceRoomPage.styled.ts
src/pages/VoiceRoomPage/EditVoiceRoomPage.tsx
src/pages/VoiceRoomPage/JoinVoiceRoomPage.tsx
src/pages/VoiceRoomPage/VoiceRoomListPage.styled.ts
src/pages/VoiceRoomPage/VoiceRoomListPage.tsx
src/pages/VoiceRoomPage/VoiceRoomPage.tsx
src/pages/VoiceRoomPage/VoiceRoomUser.tsx

#62 
정산 + 보이스룸 API 연동
branch revert 하면서 꼬이면서 좀 문제가 있는 부분이 있을 수 있어요
file change 확실하게 자신 파트랑 겹치는 부분 없는지 확인 부탁드립니다 ㅠㅠ

[FEAT] 정산 + 보이스룸 API 연동

---

src/apis/Pay/PayPageAPI.ts
src/apis/voiceroomApi.ts

baseURL 문제로 배포 상태에서 API 호출 불가능한 부분 해결

bug : change baseurl

---

src/apis/Space/SpaceJoinInfoApi.ts

fix: deploy type bug fix

---

src/apis/Chat/ChatType.ts
src/apis/LoginApi.ts
src/pages/ChatPage/ChatPage.tsx
src/pages/ChatPage/ChatSettingPage/ChatSettingPage.tsx
src/pages/ChatPage/ChattingPage/ChattingPage.tsx
src/pages/SpacePage/InviteSpace.tsx

Fix: login api

---

src/apis/Pay/PayPageAPI.ts
src/pages/PayPage/CreatePayComponents.tsx
src/pages/PayPage/CreateRequestPage.tsx

#93 
npm run build 시 에러가 발생하여 수정함

Bug#93 build error

---

src/pages/LoginPage/SignUpPage.tsx

[HOTFIX] signup axios to back url

---

src/apis/Space/SpaceCreateApi.ts
src/pages/SpacePage/AccountManage.tsx
src/pages/SpacePage/AddSpacePage.tsx
src/pages/SpacePage/AlarmManage.tsx
src/pages/SpacePage/ProfileManage.tsx
src/pages/SpacePage/SpaceOption.tsx
src/pages/SpacePage/SpacePage.tsx

Feat#96 space home

---

404.html
index.html

Config: redirect for github io

---

.github/workflows/github_pages.yml
.gitignore
src/App.tsx
src/apis/LoginApi.ts
src/pages/LoginPage/KakaoRedirection.tsx
src/pages/LoginPage/LoginPage.styled.ts
src/pages/LoginPage/LoginPage.tsx

Feat#111 카카오 로그인

---

src/pages/LoginPage/LoginModal.tsx

feat: not selected space, user view modal

---

index.html

fix: og tag link fix

---

src/App.tsx
src/apis/Space/SpaceJoinInfoApi.ts
src/pages/HomePage/HomePageMember.tsx
src/pages/SpacePage/InviteSpace2.tsx

feat : 멤버 초대 기능 추가

---

src/apis/Board/BoardPostLikeApi.ts
src/pages/BoardPage/BoardDetailpage/BoardDetailPage.tsx
src/pages/BoardPage/BoardPostItem.tsx
src/pages/BoardPage/BoardRegisterPage/BoardRegisterPage.tsx

- resolved #119 
이슈 내용 참고 바랍니다

Bug/#119: 게시판 좋아요 및 등록 버그

---

src/pages/BoardPage/BoardPage.styled.ts
src/pages/BoardPage/BoardPage.tsx
src/pages/ChatPage/ChatCreatePage/ChatCreatePage.styled.ts

Hotfix: 게시판 버튼 및 background-image 경로 이슈

---

src/pages/ChatPage/ChatCreatePage/ChatCreatePage.styled.ts
src/pages/ChatPage/ChatCreatePage/ChatCreatePage.tsx
src/pages/HomePage/HomePage.tsx

Hotfix: 이미지 component화 테스트 및 정산뷰 예외처리

---

src/pages/ChatPage/ChatCreatePage/ChatCreatePage.tsx
src/pages/LoginPage/LoginPage.tsx
src/utils/NotDevelopModal.tsx

Feat: kakao login with deploy page, / navigate chat / 개발 중 modal

---

src/components/CheckBox.tsx
src/pages/BoardPage/BoardRegisterPage/BoardRegisterPage.tsx

Hotfix: 체크박스 img 수정

---

src/App.tsx
src/pages/HomePage/HomePage.tsx
src/pages/SpacePage/AccountManage.tsx
src/pages/SpacePage/SpaceOption.tsx
src/pages/SpacePage/SpacePage.tsx
src/utils/NotDevelopModal.tsx

Feat: 개발 중인 곳 안내 modal 추가

---

src/components/TopBarText.tsx
src/pages/BoardPage/BoardBottomModal.tsx
src/pages/BoardPage/BoardDetailpage/BoardDetailPage.tsx
src/pages/BoardPage/BoardPage.tsx
src/pages/BoardPage/BoardPostItem.tsx
src/pages/BoardPage/BoardRegisterPage/BoardRegisterPage.tsx
src/pages/ChatPage/ChatCreatePage/ChatCreatePage.tsx
src/pages/ChatPage/ChatSettingPage/ChatSettingInvitePage.tsx
src/pages/ChatPage/ChatSettingPage/ChatSettingMemberPage.tsx
src/pages/HomePage/HomePageMember.tsx
src/pages/PayPage/CompleteCreatePay.tsx
src/pages/PayPage/CompletePay.tsx
src/pages/PayPage/CompleteReqDataDiv.tsx
src/pages/PayPage/CreatePayComponents.tsx
src/pages/PayPage/CreateRequestPage.tsx
src/pages/PayPage/PayPage.tsx
src/pages/PayPage/PayResult.tsx
src/pages/PayPage/ReqDataDiv.tsx
src/pages/SpacePage/AddSpacePage.tsx
src/pages/SpacePage/SpacePage.tsx
src/pages/VoiceRoomPage/JoinVoiceRoomPage.tsx
src/pages/VoiceRoomPage/VoiceRoomListPage.tsx
src/pages/VoiceRoomPage/VoiceRoomPage.tsx

lighthouse: add alt attribute in img tag

---

src/pages/ChatPage/ChatSettingPage/ChatSettingPage.tsx
src/pages/SpacePage/SpaceOption.tsx
src/utils/NotDevelopModal.tsx

[x] 버그 수정
기존에 사용했던 모달창에서  발생한 타입오류를 해결했습니다

fix: 모달 타입오류 해결

---

src/pages/ChatPage/ChatSettingPage/ChatSettingNamePage.tsx
src/pages/LoginPage/DiscordLogin.tsx

fix: build 오류

---

.github/workflows/github_pages.yml

fix: 환경변수 수정

---

documents/fix-storybook-test-ci-pr.md
package-lock.json
package.json

GitHub Actions에서 Storybook 테스트 실행 시 발생하는 `__test is not defined` 오류를 해결하기 위해 필요한 패키지를 설치했습니다. 이는 Storybook 테스트 러너의 알려진 이슈로, 공식 문서에서 권장하는 정적 빌드 방식으로 테스트를 실행하기 위한 패키지들을 추가하고 test-storybook:ci 커맨드를 수정하여 해결했습니다.(https://github.com/storybookjs/test-runner/issues/68)
Storybook 공식 문서([Running against locally built Storybooks in CI](https://github.com/storybookjs/test-runner?tab=readme-ov-file#2-running-against-locally-built-storybooks-in-ci))에 따르면, CI 환경에서 Storybook 테스트를 안정적으로 실행하기 위해서는 정적 빌드 방식을 사용하는 것이 권장됩니다.
- Storybook 테스트 CI 환경에서 필요한 패키지 설치 (concurrently, http-server, wait-on)
- 이미 설정된 `test-storybook:ci` 스크립트가 정상 작동하도록 의존성 추가
- `__test is not defined` 오류 해결을 위한 환경 구성 완료
- 추가된 패키지가 적절한지 확인 부탁드립니다
- CI 환경에서 테스트가 안정적으로 실행되는지 확인 부탁드립니다
Storybook 공식 문서에서는 CI 환경에서 테스트를 안정적으로 실행하기 위해 다음과 같은 방식을 …

Storybook 테스트 불안정성 해결

---

src/pages/QRPage/QRHome.tsx

fix: build error

---

src/pages/QRPage/QRDetail.tsx

feat : QR 다운로드

---

src/pages/QRPage/QRDetail.tsx

hotfix : 세션 이름 하드코딩 수정

---

src/apis/Pay/PayPageAPI.ts
src/apis/_createRequestOptions.ts
src/components/TimePicker.tsx
src/pages/PayPage/CompleteReqDataDiv.tsx
src/pages/PayPage/CreateRequestPage.tsx
src/pages/PayPage/GrayMyReqDataDiv.tsx
src/pages/PayPage/MyReqDataDiv.tsx
src/pages/PayPage/MyRequestPayPage.tsx
src/pages/PayPage/PayPage.tsx
src/pages/PayPage/PayResult.tsx
src/pages/PayPage/ReqDataDiv.tsx
src/pages/PayPage/RequestedPayPage.tsx

Build error 수정을 위해 PR 날립니다
현재 로컬에서는 QR의 수정을 제외하고는 다 붙은 상황이나 코드리뷰가 길어질 거 같아 여기서 끊고 올립니다

Feat#198 pay 일부분 연동 및 build error 수정

---

.github/workflows/build.yml

Build route error 발생하여 수정해보았습니다

hotfix : build route error

---

.github/workflows/build.yml

Reverts KUIT-Space/KUIT-Space-front#208

Revert "hotfix : github_pages 참고"

---

.github/workflows/build.yml

Reverts KUIT-Space/KUIT-Space-front#207

Revert "hotfix : build route error"

---

src/pages/HomePage/HomePage.styled.ts
src/pages/HomePage/HomePage.tsx
src/pages/PayPage/MyReqDataDiv.tsx

- cursor:pointer 처리 빠져있던 부분 추가 (정산)
- /qr/home으로의 진입점이 없어서 홈페이지에서 설정 누르고 들어갈 수 있게 추가
- 홈페이지 하단이 bottom navigation bar에 가리던 현상 해결

feat : QR Home 진입점 추가

---

.github/workflows/build.yml

Update GitHub pages.yml
